### ISSUE TITLE
Imapflow stops listening for new imap events after while

### ISSUE THREAD

**Issue by all43** [andris9/imapflow#14]
Hi, and thank you for the amazing library!

I have an issue which is difficult to reproduce.

Imapflow version: **1.0.39**, same behaviour with older versions as well

In my app I'm listening for _exists_ event to check for a new mail.
It works fine, but after few days (sometime few hours) _exists_ event stops firing with no sign that something went wrong.
I suspect that connection breaks, without being detected. (no _error_ event firing)
If I restart my app it works again.

Log output:
```
{"level":20,"time":1586405156088,"pid":18,"hostname":"49d844c5f708","component":"imap-connection","cid":"ph1z3tufntqm37xppwxb","src":"s","msg":"* OK Still here","cid":"ph1z3tufntqm37xppwxb"}
{"level":20,"time":1586405276167,"pid":18,"hostname":"49d844c5f708","component":"imap-connection","cid":"ph1z3tufntqm37xppwxb","src":"s","msg":"* OK Still here","cid":"ph1z3tufntqm37xppwxb"}
{"level":20,"time":1586405396284,"pid":18,"hostname":"49d844c5f708","component":"imap-connection","cid":"ph1z3tufntqm37xppwxb","src":"s","msg":"* OK Still here","cid":"ph1z3tufntqm37xppwxb"}
{"level":20,"time":1586405459550,"pid":18,"hostname":"49d844c5f708","component":"imap-connection","cid":"ph1z3tufntqm37xppwxb","src":"c","msg":"breaking IDLE"}
```

 Is there something I can do to check if connection still alive?

**Comment by andris9** [comment]
Is the last log line with "breaking IDLE" the final log and after that nothing happens at all?

**Comment by all43** [comment]
> Is the last log line with "breaking IDLE" the final log and after that nothing happens at all?
Exactly

**Comment by andris9** [comment]
Do you have a 'close' event handler set for ImapFlow? That `breaking IDLE` message is probably caused by lost connection, you should catch it and create a new connection yourself.

```js
let client= new ImapFlow(...)
client.on('close', (...args) => {
  // handle disconnect
});
```

**Comment by all43** [comment]
Yes, I've missed this.
I expected _error_ event instead of _close_ but error only firing during initial connection.
Probably it worth highlighting in the docs.
Thank you!

**Comment by andris9** [comment]
Yes, you're right, I should make it more clear in the docs. Some libraries reconnect automatically making disconnects seamless, ImapFlow does not do this and expects the user to handle reconnects.
