### ISSUE TITLE
Disable logger option

### ISSUE THREAD

**Issue by goraSi** [andris9/imapflow#18]
**Is your feature request related to a problem? Please describe.**
Currently there is no clear option to disable logger completely.

**Describe the solution you'd like**
Disable logger.

**Describe alternatives you've considered**
Disable logging with option.

`const client = new ImapFlow({ logger: false })`

**Comment by mesadhan** [comment]
I'm not also able to Disable logger that logger. It's really painful.

**Comment by jniles** [comment]
Just a quick note - it's possible to disable the logs by using pino's `silent` option.  I agree it should be an option, but you can get rid of the logs currently by doing:
```js
const pino = require('pino')();
pino.level = 'silent';
const client = new ImapFlow({ logger : pino });
```

**Comment by mesadhan** [comment]
Thanks  @jniles 

```
const pino = require('pino')();
pino.level = 'silent';
const client = new ImapFlow({ logger : pino });
```
It's working for me.

**Comment by jasonk** [comment]
For anyone else who winds up here and then finds that the previous instructions don't work any more, this is the only way I could find to suppress the logging:

```javascript
const client = new ImapFlow( { ...config, logger  : {} } );
```

**Comment by tirathsharma098** [comment]
> @jasonk If I use `logger: {}`, it gives me an error.
> 
> I used `logger: false` to make it work

Thanks it worked
