### ISSUE TITLE
Unable to receive messages in realtime

### ISSUE THREAD

**Issue by georgyfarniev** [andris9/imapflow#29]
**Describe the bug**
When pooling email inbox using imapflow and new email arrives there, imapflow seems to be unable of receiving it.

**To Reproduce**
1. Run script from this gist against an empty mailbox: https://gist.github.com/georgyfarniev/8c9893a6f5906119bb53753978b6d976
2. Manually send email to this mailbox from another email
3. Observe only undefined value for message.uid in console (since it false, which means nothing was received, I assume)

**Expected behavior**
imapflow should be able to fetch new message

**Desktop (please complete the following information):**
 - OS: Windwos 10
 - Runtime: NodeJS v12.16.3 
 - Version of imapflow: 1.0.51

**Additional context**
I double checked this issue, and I can see newly arrived email via thunderbird, but imapflow shows nothing in runtime. If I restart script, it will show message, so problem occurs only if message arrives during runtime. If something is wrong with code, please give me any hint how to solve this issue. Thanks for working on imapflow!

**Comment by andris9** [comment]
You can't receive new emails with a looping FETCH as by the protocol IMAP server is not allowed to send notifications for that command. You have to use IDLE or NOOP.

**Comment by georgyfarniev** [comment]
@andris9 thanks, I never worked with IMAP so I missed that part.
