### ISSUE TITLE
Large memory issue when appending email to a mailbox

### ISSUE THREAD

**Issue by duyhotan2000** [andris9/imapflow#32]
Hi,

I am using `mailcomposer` to create a mail buffer with `compile().build()` to feed it into append function of imapflow and it takes a lot of memory.
I think whether `imapflow` append could support Stream input or not? Is this possible then I will try to implement it to lessen the memory taken when creating the full message buffer.

Thank you!

**Comment by andris9** [comment]
IMAP syntax requires the exact byte size beforehand so it is not possible to stream arbitrary data.
