### ISSUE TITLE
Can not import FetchMessageObject type from imapflow

### ISSUE THREAD

**Issue by dobromyslov** [andris9/imapflow#33]
**Describe the bug**
FetchMessageObject is located in the file `types.d.ts` but it's out of the module scope therefore it's impossible to import as:
`import { ImapFlow, FetchMessageObject } from "imapflow";`

**To Reproduce**
1. `npm install imapflow`
2. `import { ImapFlow, FetchMessageObject } from "imapflow";`

**Expected behavior**
`FetchMessageObject` type should be exported along with the module.

**Additional context**
imapflow@1.0.51

**Comment by dobromyslov** [comment]
I've just read GNU Affero terms and don't want to participate in thip project.

**Comment by andris9** [comment]
@dobromyslov I understand if the license is not suitable for your use case. As an alternative you can use MIT-licensed [node-imap](https://github.com/mscdex/node-imap) or [imap-simple](https://github.com/chadxz/imap-simple) (not a separate IMAP client but a wrapper around node-imap), these are the most established projects in this field.
