### ISSUE TITLE
[Question] Is it possible to fetch messages in a descending order?

### ISSUE THREAD

**Issue by mohammedSlimani** [andris9/imapflow#37]
I would love to implement a way to show emails as in gmail, last received is first shown. So I needed the feature to fetch emails in using pagination.
the way I tried to implement it is by implementing my own descending fetch, and running a regex on the subject: 

```
/**
   * Generator for fetching an email starting from the most recent one
   * This generator generates the latest email that respects a subject regex
   * @param {number} start - uid from where to start getting the emails in a descending order
   * @param {string} subject - regex subject of the email that needs to be respected 
   * @return {AsyncGenerator<null, void, *>}
   */
async* fetchDescending (start, subject) {
    let nextEmailUid = start

    // returning the email using the nextEmailUid
    while (nextEmailUid > 0) {
      // is it possible to pass some searching criteria to fetchOne ? 
      let nextEmail = await client.fetchOne(nextEmailUid, { envelope: true, uid: true }, { uid: true } )

      // Yielding the email or marking it as read
      if (nextEmail) {
        // returning it only if it has the right Subject type!
        if (extractSubject(nextEmail.envelope.subject) === subject) {
          yield nextEmail
        }
      }

      // decrementing the email uid and resetting the nextEmail to null
      nextEmailUid --
    }
  }
```

doing it this way is very slow, for an inbox of 80 mails it takes about 6 seconds...
my question is the following: 
- Can I fetch emails in a descending manner something like `fetch("*-10:*")` to fetch the last 10 emails? 
- Is it possible to fetch emails that respect a certain regex? 

thank you very much @andris9 and other contributors for this very useful module.

**Comment by andris9** [comment]
IMAP allows you to fetch emails by sequence numbers where 1 is the oldest email and `*` is the newest. So if you want to list messages from newest to latest then you need to at first check how many messages there is and then start fetching these messages in batches.

Eg. if there is 100 emails then you'd fetch `91:100` first, then `81:90`, `71:80` and all the way down to `1:10`. You can check how IMAP API does the exact same thing [here](https://github.com/andris9/imapapi/blob/51faea114248ec9c436ee5a2cd431a54b6758229/lib/mailbox.js#L1132) (lists messages by "pages").

There is no way to make regex requests. You can use SEARCH to retrieve matching message numbers and then FETCH based on these numbers, but it has it's limitations.

**Comment by mohammedSlimani** [comment]
Thank you very much for explaining that the sequence number 1 actually refers to the oldest message. Knowing that helps a lot.
