### ISSUE TITLE
Unable to download file using download() method

### ISSUE THREAD

**Issue by eriklumbela** [andris9/imapflow#42]
**Unable to download file using download() method**
I'm trying to download a file using the download() method, but so far I was unable to do it correctly.

**To Reproduce**
I retrieved an e-mail containing a pdf, and from there i'm trying to get the file
```
let message = await client.fetchOne(sequenceString, { bodyStructure: true });
      const structuresArray = flattenBodyStructure(message.bodyStructure);
      for (const structure of structuresArray) {
        if (structure.type === 'application/pdf'){
          console.log(structure);
          let {meta, content} = await client.download(sequenceString, structure.part);

          let writeStream = fs.createWriteStream(path.resolve(__dirname, `../downloads/${Date.now()}-${meta.filename}`));

          writeStream.write(content, meta.encoding);

          writeStream.on('finish', () => {
              console.log('wrote all data to file');
          });

          writeStream.end();
        }
      }
```
*flattenBodyStructure is just a convenience method to retrieve the different email parts*

**Expected behavior**
I expect to be able to download the pdf and open it
But the file is corrupt. It seems I do not understand the documentation correctly for the download method.

**Comment by andris9** [comment]
`content` is a stream not a buffer or string. You could pipe it like this: `content.pipe(writeStream);`

**Comment by eriklumbela** [comment]
thanks! I updated the docs: https://github.com/andris9/imapflow/pull/43
