### ISSUE TITLE
Timeout for `client.getMailboxLock()` when there is a network disconnection

### ISSUE THREAD

**Issue by gsommavilla** [andris9/imapflow#48]
If connection goes down while doing `client.getMailboxLock('INBOX')`,
I noticed that the execution of that function gets blocked for 15 or
16 minutes; after that, the `ENETUNREACH` error is raised.

This behaviour can be tested with a minimal working example like the
code I posted in https://github.com/andris9/imapflow/issues/47,
running the code and then disconnecting the NetworkManager client.
I tested this with Debian testing and node v.12.

Is there a way to shorten that timeout?

**Comment by andris9** [comment]
You could try the latest version of ImapFlow to see if there is a difference

**Comment by gsommavilla** [comment]
I confirm that with 1.0.58 the problem is solved (error is caught).
Thank you very much!

NB: In order to have a faster timeout I have changed the timeout to
all these variables in `./node_modules/imapflow/lib/imap-flow.js`:

```
  const CONNECT_TIMEOUT  = 9 * 1000; // original value: 90 * 1000;
  const GREETING_TIMEOUT = 9 * 1000; // original value: 16 * 1000;
  const UPGRADE_TIMEOUT  = 9 * 1000; // original value: 10 * 1000;
  const SOCKET_TIMEOUT   = 9 * 1000; // original value: 5 * 60 * 1000;
```
