### ISSUE TITLE
Extend german translations for special use

### ISSUE THREAD

**Issue by yawgmoth1806** [andris9/imapflow#49]
**Is your feature request related to a problem? Please describe.**

Recently I wanted to use imapflow to handle an email account with the following host: outlook.office365.com.
Unfortunately the boxes don't contain the capability `XLIST` or `SPECIAL-USE` therefore the following string comparison happens in `special-use.js`:

> let name = folder.name.toLowerCase().trim();
> return Object.keys(module.exports.names).find(flag => module.exports.names[flag].includes(name));

In this case the folders german names differ slightly from what is currently available and therefore the `specialUseFlag` is missing for several boxes.
I am not able to rename boxes.

**Describe the solution you'd like**

Since the folders german names aren't anything special, but more general terms, I'd like to add those to the corresponding arrays in `special-use.js`.

**Additional context**

I'd like to create a PR, but unfortunately I cannot create branches. How can I contribute?

**Comment by andris9** [comment]
If it's only folder names, then you could list these here as a comment, I'll add these myself.

In general, for PR's, you don't need to create a branch. Instead you should fork the repo, do the changes in your forked copy and then come here to open a PR.

**Comment by andris9** [comment]
Added these values to the list (59797dad13922f4325518ab7821d7cc7bc3bf8b9), thanks!
