### ISSUE TITLE
Question: syntax of 'Date' operand in messageDelete({before: Date})

### ISSUE THREAD

**Issue by paul-bell** [andris9/imapflow#52]
Thank you very much for this really fine piece of work; most helpful.

I cannot get messageDelete to work with the _before_ SearchObject property. 

I set the value of _before_ to a _new Date()_ which represents, say, an hour ago. There are definitely messages in the inbox that were received prior to that.

Where your documentation says 'Date' does that mean a JavaScript Date?

Also, what is the correct format for a date operand expressed as a string?

Thanks again!

-Paul

**Comment by paul-bell** [comment]
Hello again,

FWIW, _{all: true}_ works, but I need to delete by _before_.

Please let me know, thanks.

**Comment by andris9** [comment]
IMAP search precision is one day, so you can use a Date object but only the date part of it is used. This is a protocol limitation, so there is no workaround. You should probably search for a larger time window and then filter out messages that don't match on the client side.

**Comment by paul-bell** [comment]
Thank you, Andris. 

I am passing a JavaScript Date object whose value is, say, two days ago. Thus, I expect anything older than ('before') two days ago to be deleted from the mailbox. But that is not happening.

Can you please tell me the syntax for a date **string** that can be used with {before: <dateString>}? I will try that.

Cordially,

Paul

**Comment by paul-bell** [comment]
FWIW, I think **my** misapprehension of the phenomena has been dispelled. 

Indeed, emails _before_ a certain day are being deleted. It just seems to take the IMAP server a long-ish time to accomplish this.

Thank you.
